gedge-platform/gm-center

gmc_database_api_server/app/api/clusters.go
gmc_database_api_server/app/api/custom2.go
gmc_database_api_server/app/api/monitoring.go
gmc_database_api_server/app/routes/routes.go

monitoring

---

gmc_database_api_server/app/api/callListModel.go

callListmodel update

---

gmc_database_api_server/app/api/deployment.go
gmc_database_api_server/app/common/Util.go

deployment util 수정

---

gmc_database_api_server/app/api/callListModel.go
gmc_database_api_server/app/api/clusters.go
gmc_database_api_server/app/api/deployment.go
gmc_database_api_server/app/api/projects.go
gmc_database_api_server/app/api/services.go
gmc_database_api_server/app/common/Util.go
gmc_database_api_server/app/common/httpUtil.go
gmc_database_api_server/app/model/deployment.go

namespace list 수정

---

gmc_database_api_server/app/api/pod.go
gmc_database_api_server/app/common/Util.go

util.go update -pod

---

gmc_database_api_server/app/api/clusters.go
gmc_database_api_server/app/api/projects.go
gmc_database_api_server/app/common/Util.go
gmc_database_api_server/app/model/clusters.go

master worker node 구분
allocatable,capacity,resource 정보 추가

getCluster 수정

---

gmc_database_api_server/app/api/callListModel.go
gmc_database_api_server/app/model/deployment.go

workspaceName add

---

gmc_database_api_server/app/api/projects.go
gmc_database_api_server/app/common/Util.go
gmc_database_api_server/app/model/deployment.go

deployment detail add replicaName

deployment detail add replicaName

---

gmc_database_api_server/app/common/Util.go
gmc_database_api_server/app/model/deployment.go
gmc_database_api_server/app/model/service.go

service detail pod list

---

gmc_database_api_server/app/api/event.go
gmc_database_api_server/app/api/projects.go
gmc_database_api_server/app/model/clusters.go
gmc_database_api_server/app/model/event.go
gmc_database_api_server/app/model/projects.go
gmc_database_api_server/app/routes/routes.go

event clusterName add

---

gmc_api_gateway/app/api/callListModel.go
gmc_api_gateway/app/api/pvc.go
gmc_api_gateway/app/model/pv.go
gmc_api_gateway/app/model/pvc.go
gmc_api_gateway/app/routes/routes.go

pv list update
pvc list update
pvc detail update

pv,pvc update

---

gmc_api_gateway/app/controller/cluster.go
gmc_api_gateway/app/controller/workspace.go
gmc_api_gateway/app/model/cluster.go

cluster JOIN to workspace, update

cluster JOIN to workspace, update

---

gmc_api_gateway/app/api/projects.go
gmc_api_gateway/app/model/projects.go
gmc_api_gateway/app/routes/routes.go

/gmcapi/v1/userProjects
-> userProjectList
/gmcapi/v1/userProjects/{userProjectName}
-> userProjectDetail
/gmcapi/v1/userProjects/{userProjectName}?workspace={workspaceName}
-> userProjectDetail workspace filter 적용
/gmcapi/v1/systemProjects
-> systemProjectList
/gmcapi/v1/systemProjects/{systemProjectName}
-> systemProjectNameList 
/gmcapi/v1/systemProjects/{systemProjectName}?cluster={clusterName}
-> systemProjectDetail

project Modify

---

gmc_api_gateway/app/api/callListModel.go
gmc_api_gateway/app/api/deployment.go
gmc_api_gateway/app/api/projects.go
gmc_api_gateway/app/common/Util.go
gmc_api_gateway/app/model/pod.go
gmc_api_gateway/app/model/service.go

service, deploy, pod involved data modify

service, deploy, pod involved data modify

---

gmc_api_gateway/app/api/job.go
gmc_api_gateway/app/api/projects.go
gmc_api_gateway/app/model/job.go

modify projectList

---

gmc_api_gateway/app/api/cronjob.go
gmc_api_gateway/app/api/job.go
gmc_api_gateway/app/api/statefulset.go
gmc_api_gateway/app/common/Util.go
gmc_api_gateway/app/model/cronjob.go
gmc_api_gateway/app/model/job.go

cronjob modify

---

gmc_api_gateway/app/api/projects.go
gmc_api_gateway/app/api/workspaces.go
gmc_api_gateway/app/common/error.go
gmc_api_gateway/app/routes/routes.go

duplicate check

---

gmc_api_gateway/app/api/projects.go
gmc_api_gateway/app/api/workspaces.go
gmc_api_gateway/app/model/workspaces.go

Reverts gedge-platform/gm-center#110

Revert "Yby654"

---

gmc_api_gateway/app/api/nowMonit.go
gmc_api_gateway/app/api/projects.go
gmc_api_gateway/app/api/workspaces.go
gmc_api_gateway/app/common/Util.go
gmc_api_gateway/app/model/workspaces.go
gmc_api_gateway/go.mod

workspace detail

---

gmc_api_gateway/app/common/httpUitls.go
gmc_api_gateway/app/controller/vm.go
gmc_api_gateway/app/routes/routes.go

CB-Spider Manage VM Update

---

gmc_api_gateway/app/controller/auth.go
gmc_api_gateway/app/controller/cluster.go
gmc_api_gateway/app/controller/dashboard.go
gmc_api_gateway/app/controller/deployment.go
gmc_api_gateway/app/controller/monitoring.go
gmc_api_gateway/app/controller/project.go
gmc_api_gateway/app/model/cluster.go
gmc_api_gateway/app/model/dashboard.go
gmc_api_gateway/app/model/project.go
gmc_api_gateway/app/routes/routes.go
gmc_api_gateway/docs/docs.go
gmc_api_gateway/docs/swagger.json
gmc_api_gateway/docs/swagger.yaml
gmc_api_gateway/go.mod
gmc_api_gateway/main.go

- totalDashboard  ( coreCloud X )
- createCluster (address, Geocoder update)

[220728] totalDashboard , createCluster update

---

gmc_api_gateway/app/common/Util.go
gmc_api_gateway/app/controller/dashboard.go
gmc_api_gateway/app/controller/monitoring.go
gmc_api_gateway/app/model/dashboard.go
gmc_api_gateway/app/routes/routes.go

[220810]service dashboard
- monitoring update

[220810]service dashboard

---

gmc_api_gateway/app/controller/cluster.go
gmc_api_gateway/app/controller/monitoring.go
gmc_api_gateway/app/controller/nowMonit.go

[220811] cluster monitoring modify

[220811] cluster monitoring modify

---

gmc_api_gateway/app/common/httpUtil.go
gmc_api_gateway/app/controller/ceph.go
gmc_api_gateway/app/controller/monitoring.go

[221219]merge

---

gmc_api_gateway/app/common/httpUitls.go
gmc_api_gateway/app/controller/dashboard.go
gmc_api_gateway/app/controller/monitoring.go
gmc_api_gateway/app/controller/vm.go
gmc_api_gateway/go.mod
gmc_api_gateway/main.go

[230102] redis 캐시 적용
